spring:
  application:
    name: wedit-server
  profiles:
    active: local

server:
  port: 8080

app:
  cors:
    allowed-origins: http://localhost:3000,http://localhost:5173,http://localhost:8081

management:
  endpoints:
    web:
      exposure:
        include: health
